### ISSUE TITLE
`npm ci` failing

### ISSUE THREAD

**Issue by nopeless** [jurassicjs/nuxt3-fullstack-tutorial#12]
branch is `section/2/auth`

similar to #5 but this is explicitly the repository's fault as npm ci shouldn't fail since it uses locked versions

**Comment by rohrig** [comment]
I gave this a shot locally. The first try did fail becasue:

"The `npm ci` command can only install with an existing package-lock.json"

This makes sense because I've only used yarn with produces a yarn.lock. 

After running npm i once, which creates the package-lock.json, npm ci ran without errors. 

So the solution would be to run npm i at least once locally, then you should be good to go. I'll close this. If you still have issues let me now.

**Comment by nopeless** [comment]
sorry didn't see it was yarn.lock my bad
